version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_HOME=/var/app
    environment:
      DBM_MIGRATION_STORE: ./migrations
      DBM_DATABASE: "host=db; user=root; password=password; database=keijiban;"
      DBM_TIMESTAMP_FILENAMES: "on"
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/app
    links:
      - db

  db:
    image: mysql:5.7.17
    environment:
      MYSQL_DATABASE: keijiban
      MYSQL_ROOT_PASSWORD: password
